name: Limbo CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Clone git repository under $GITHUB_WORKSPACE
      uses: actions/checkout@v2

    - name: Install all dependencies
      run: npm install

    - name: Deploy on ruben.quast.fr
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "./dist/client"
        remoteDir: "/public/www/projects/limbo"
