name: Limbo CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Clone git repository under $GITHUB_WORKSPACE
      uses: actions/checkout@v4

    - name: Install all dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy on ruben.quast.fr
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "./dist/client"
        remoteDir: "/projects/limbo"
